Repository SwanandD121/FeatherPerfect_fe, pull requests merged in 2024-10, with the labels that each got.

#20 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, gssoc-ext, level 2, hacktoberfest-accepted

#57 #Add Code_Of_Conduct.md
  Code_Of_Conduct.md
Labels: documentation, good first issue, gssoc-ext, level 1, hacktoberfest-accepted

#68 Update explore input & Improve UI
  src/Components/LogoSearch/LogoSearch.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#72 Addition of All Contributors | Issue #62
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#74 Added How to Create a PR
  CONTRIBUTING.md
  docs/fork.png
  docs/git.md
Labels: documentation, gssoc-ext, level2, hacktoberfest-accepted

#77 added password validation
  src/pages/Auth/Auth.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#85 Logout not redirecting to login page
  src/App.js
  src/Components/InfoCard/InfoCard.jsx
Labels: bug, gssoc-ext, level2, hacktoberfest-accepted

#97 Fixes #88: replace hyperlink with a toggle button to switch between light mode and dark mode
  src/pages/Auth/Auth.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#102 [FIX] : Profile Page Scroll Issue Fixed
  src/Components/ProfileCard/ProfileCardH.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#91 Added logged in message
  src/pages/Auth/Auth.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#106 [FEAT] ; Notifications Message UI Added
  src/Components/NotificationModal/NotificationCard.jsx
  src/Components/NotificationModal/NotificationModal.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#55 Update for Hacktoberfest
  README.md
Labels: hacktoberfest-accepted

#161 Modified README.md file & Created LICENSE File for project
  LICENSE
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#156 [FEAT] : Emojis Can Be Used While Sharing Experience
  package-lock.json
  package.json
  src/Components/ExperienceModal/ExperienceModal.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#150 Added Conditional Logic for Content Sharing in PostShare Component
  src/Components/PostShare/PostShare.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#168 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yml
Labels: documentation, gssoc-ext, level1, hacktoberfest-accepted
